# Utilise une image Python de base
FROM python:3.10-alpine

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie le script Python dans le conteneur
COPY generate_number.py .

# Exécute le script Python
CMD ["python", "generate_number.py"]
